import os
import sys
from PyQt6.QtCore import *
from PyQt6.QtWidgets import *


class VersionInfoWindow(QDialog):
    def __init__(self, parent):
        super().__init__(parent, Qt.WindowType.Window)

        self.setModal(False)

        version_info = self.get_version_info()

        label = QLabel(version_info, self)

        button_box = QDialogButtonBox(QDialogButtonBox.StandardButton.Close)
        button_box.rejected.connect(self.reject)

        layout = QVBoxLayout(self)
        layout.addWidget(label)
        layout.addWidget(button_box)

    def get_version_info(self) -> str:
        """ If the app is bundled, returns the version info which was generated by the installer script. """
        if getattr(sys, 'frozen', False) and hasattr(sys, '_MEIPASS'):
            # running in a PyInstaller bundle

            version_path = os.path.join(sys._MEIPASS, "version.txt")

            with open(version_path, "r") as f:
                version = f.read()
                return version
        else:
            # running in a normal Python process

            return "version info not found, app is not bundled"
